# Generated by Django 5.2.2 on 2025-06-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convidados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_presente', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='presentes')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('importancia', models.PositiveIntegerField()),
                ('reservado', models.BooleanField(default=False)),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='convidados.convidados')),
            ],
        ),
    ]
